name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-run-containers:
    name: Verify Docker Containers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run Docker Compose
        run: |
          docker-compose up -d --build

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for API and DB to start..."
          sleep 20
          docker-compose ps

      - name: Check ASP.NET API
        run: |
          echo "Checking ASP.NET API..."
          curl -f http://localhost:8080 || (echo "API is not responding!" && exit 1)

      - name: Check PostgreSQL
        run: |
          echo "Checking PostgreSQL..."
          docker exec $(docker-compose ps -q db) pg_isready -U postgres || (echo "PostgreSQL is not ready!" && exit 1)

      - name: Shut down Docker Compose
        run: docker-compose down
